services:
  api:
    build: .
    pull_policy: build
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - API_KEY=${API_KEY}
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`${DOMAIN}`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls.certresolver=letsencrypt"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
    networks:
      - traefik-network
      
networks:
  traefik-network:
    external: true
 

