version: '3'

services:
  api:
    build: .
    pull_policy: build
    ports:
      - "3000:3000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - API_KEY=${API_KEY}
